apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "system-api.fullname" . }}-worker
  labels:
    {{- include "system-api.labels" . | nindent 4 }}
  {{- with .Values.worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "system-api.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "system-api.selectorLabels" . | nindent 8 }}
        component: worker
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./apps/system-api/docker-entrypoint.sh
          args:
            - node
            - apps/system-api/dist/worker/main.js
          {{- $envList := concat (default (list) .Values.commonEnv) (default (list) .Values.worker.env) }}
          {{- if $envList }}
          env:
{{ toYaml $envList | indent 12 }}
          {{- end }}
          {{- $envFromList := list }}
          {{- if .Values.secret.enabled }}
          {{- $envFromList = append $envFromList (dict "secretRef" (dict "name" (include "system-api.secretName" .))) }}
          {{- end }}
          {{- range .Values.additionalSecrets }}
          {{- $envFromList = append $envFromList (dict "secretRef" (dict "name" .)) }}
          {{- end }}
          {{- range .Values.commonEnvFrom }}
          {{- $envFromList = append $envFromList . }}
          {{- end }}
          {{- range .Values.worker.envFrom }}
          {{- $envFromList = append $envFromList . }}
          {{- end }}
          {{- if $envFromList }}
          envFrom:
{{ toYaml $envFromList | indent 12 }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
